import {answers,guesses} from './data.js';
import {guesses as generalGuesses} from "./1-data.js";
export const MODES={facil:{label:'Fácil',attempts:8,hints:2},avanzado:{label:'Avanzado',attempts:6,hints:0},dificil:{label:'Difícil',attempts:5,hints:0}};
export const clean=(s)=>s.toUpperCase().replace(/Ñ/g,'\uE000').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\uE000/g,'Ñ').replace(/[^A-ZÑ]/g,'');
export function grade(guess,answer){const g=Array.from(clean(guess)),a=Array.from(clean(answer)),out=Array(5).fill(0);for(let i=0;i<5;i++)if(g[i]===a[i]){out[i]=2;a[i]=null}for(let i=0;i<5;i++)if(!out[i]){const j=a.indexOf(g[i]);if(j!==-1){out[i]=1;a[j]=null}}return out}
export function constraints(history,word){const w=Array.from(clean(word));let min={},max={},fixed=Array(5).fill(null),forbidden=Array.from({length:5},()=>new Set());for(const row of history){let count={},total={};row.guess.split('').forEach(c=>total[c]=(total[c]||0)+1);row.grade.forEach((v,i)=>{const c=row.guess[i];if(v){count[c]=(count[c]||0)+1;if(v===2)fixed[i]=c;else forbidden[i].add(c)}else forbidden[i].add(c)});for(const [c,n] of Object.entries(total)){min[c]=Math.max(min[c]||0,count[c]||0);if(count[c]<n)max[c]=Math.min(max[c]??5,count[c]||0)}}for(let i=0;i<5;i++){if(fixed[i]&&w[i]!==fixed[i])return `La letra ${fixed[i]} va en la posición ${i+1}.`;if(forbidden[i].has(w[i]))return `La letra ${w[i]} no va en la posición ${i+1}.`}for(const [c,n] of Object.entries(min))if(w.filter(x=>x===c).length<n)return `Tenés que usar la letra ${c}.`;for(const [c,n] of Object.entries(max))if(w.filter(x=>x===c).length>n)return `La letra ${c} aparece como máximo ${n} veces.`;return null}
export function dayKey(date=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Montevideo',year:'numeric',month:'2-digit',day:'2-digit'}).format(date)}
export function answerFor(day){const n=Math.floor((Date.parse(`${day}T12:00:00Z`)-Date.parse('2026-09-25T12:00:00Z'))/86400000);const idx=((n%answers.length)+answers.length)%answers.length;return answers[idx]}
export const valid=(s)=>guesses.has(clean(s)) || generalGuesses.has(clean(s)) || clean(s)==='AEIOU';
export function storeKey(day,mode){return `leydle:v1:${day}:${mode}`}
export function load(day,mode){try{const p=JSON.parse(localStorage.getItem(storeKey(day,mode)));if(p&&Array.isArray(p.rows)&&p.rows.length<=MODES[mode].attempts&&p.rows.every(r=>typeof r==='string'&&/^[A-ZÑ]{5}$/.test(r)))return p.rows}catch{}return []}
export function save(day,mode,rows){try{localStorage.setItem(storeKey(day,mode),JSON.stringify({rows}))}catch{}}
export function stats(){try{const records=JSON.parse(localStorage.getItem('leydle:v1:results'))||{};let dates=[...new Set(Object.keys(records).filter(k=>records[k].win).map(k=>k.split(':')[0]))].sort().reverse(),streak=0,today=dayKey(),yesterday=dayKey(new Date(Date.now()-86400000)),cursor=dates.includes(today)?today:yesterday;while(dates.includes(cursor)){streak++;cursor=dayKey(new Date(Date.parse(cursor+'T12:00:00Z')-86400000))}return {played:Object.keys(records).length,wins:Object.values(records).filter(x=>x.win).length,streak}}catch{return {played:0,wins:0,streak:0}}}
export function record(day,mode,win){try{const key='leydle:v1:results',d=JSON.parse(localStorage.getItem(key))||{};d[`${day}:${mode}`]={win};localStorage.setItem(key,JSON.stringify(d))}catch{}}
export function shareText(day,mode,rows,answer){const m=MODES[mode],blocks={0:'⬛',1:'🟨',2:'🟩'};return `Leydle ${day} · ${m.label} ${rows.at(-1)===answer?rows.length:'X'}/${m.attempts}\n`+rows.map(r=>grade(r,answer).map(n=>blocks[n]).join('')).join('\n')+'\nhttps://lucasramos.uy/normativa/leydle/'}
